version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.21
  pre_build:
    commands:
      - go version
      - printenv
      - go mod download
  build:
    commands:
      - go test -cover ./...
  post_build:
    commands:
      - echo "build completed"

#cache:
#  paths:
#    - /go/pkg/mod/**/*