version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.20
  pre_build:
    commands:
      - go version
      - docker --version
      - printenv
  build:
    commands:
      - REV_TAG=rev_$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-10)
      - docker build -t ${ecr_image}:$REV_TAG .
      - docker tag ${ecr_image}:$REV_TAG ${ecr_image}:latest
      - docker images
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin ${ecr_auth_endpoint}
      - docker push ${ecr_image}:$REV_TAG
      - docker push ${ecr_image}:latest
  post_build:
    commands:
      - mkdir -p scripts/dev
      - cp scripts/ecs-appspec-dev.yml scripts/dev/appspec.yml
      - mkdir -p scripts/prod
      - cp scripts/ecs-appspec-prod.yml scripts/prod/appspec.yml
      - echo "build completed"

artifacts:
  secondary-artifacts:
    BuildOutputArtifactDev:
      files:
        - scripts/dev/appspec.yml
      discard-paths: yes
    BuildOutputArtifactProd:
      files:
        - scripts/prod/appspec.yml
      discard-paths: yes

cache:
  paths:
    - /go/pkg/mod/**/*