version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.20
  pre_build:
    commands:
      - go version
      - printenv
  build:
    commands:
      - go test
      - env GOOS=linux GOARCH=arm64 go build
  post_build:
    commands:
      - echo "build completed"

artifacts:
  files:
    - go-rest-sample
    - appspec.yml
    - scripts/**/*

cache:
  paths:
    - /go/pkg/mod/**/*