version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.20
  pre_build:
    commands:
      - go version
      - printenv
  build:
    commands:
      - go test
  post_build:
    commands:
      - echo "build completed"

cache:
  paths:
    - /go/pkg/mod/**/*